### ISSUE TITLE
Package doesn't work well with ES6

### ISSUE THREAD

**Issue by mugishap** [quarksgroup/paypack-js#7]
### Issue Description
Paypacks-js is an essential package that facilitates payment processing. As the JavaScript ecosystem has evolved, the adoption of ECMAScript 6 (ES6) features has become widespread, providing developers with enhanced syntax and improved programming paradigms. Therefore, I would like to request an update for Paypack-js to ensure compatibility with ES6 standards.

### Benefits of ES6 Compatibility
- **Enhanced Syntax:** ES6 introduces arrow functions, template literals, destructuring, and more. An update would allow developers to take full advantage of these features.
- **Modularity with Modules:** ES6 modules enable better code organization and encapsulation. An update would allow developers to seamlessly integrate Paypack-js into their ES6 codebase.
- **Class Definitions:** ES6 classes offer a more structured and object-oriented approach to development. Updating Paypack-js to work with classes would be advantageous.
- **Improved Performance:** ES6 code optimizations can result in better runtime performance. Compatibility would lead to more performant payment processing.

### Request
I kindly request that the maintainers consider the importance of ES6 compatibility for Paypack-js and initiate the necessary changes. Given the increasing adoption of ES6 and its advantages for modern JavaScript development, this update would greatly benefit developers who rely on paypack-js for payment-related functionality.

I'm willing to contribute to this update process by assisting with testing, providing feedback, and contributing code changes if required.

Thank you for your attention to this matter, and I look forward to the possibility of an ES6-compatible paypack-js in the future.

### Additional Information
- **My Contact Information:** [mugishap](https://github.com/mugishap)

**Comment by fredshema** [comment]
@mugishap I will look into this I will update you when I create a pull request

**Comment by fredshema** [comment]
[0.2.1](https://github.com/quarksgroup/paypack-js/commit/407f35091d7b13c076a452ce5f3bafb0b4e70c8f)
